### ISSUE TITLE
Support Horizontal?

### ISSUE THREAD

**Issue by FengDeng** [airbnb/AloeStackView#13]

**Comment by marlimox** [comment]
Hi @FengDeng, this is a great suggestion and something I think AloeStackView should support. It could take a bit of refactoring of the internals of the library to get it working but it should be perfectly achievable! Please feel free to add this support if it’s something you’re interested in working on.

**Comment by FengDeng** [comment]
@marlimox, I'd like to, but I'm not good at layoutAnchor. I usually use snapkit.Well,I will try it.

**Comment by FengDeng** [comment]
@marlimox  Maybe this is not the best solution, I modified some code to implement this ,I realize that this is for the purpose of static tableview or less cell tableview.
And using stackview and scrollview is easy to support Horizontal.There is no need to modify it.

**Comment by marlimox** [comment]
That makes sense. However, I still think this could be a useful feature to support. And it should be relatively straightforward to implement, since in principle UIStackView can easily be switched to a horizontal axis.

I’ll leave this issue open in case we decide to pursue this idea sometime in the future.

Thanks for your input @FengDeng!

**Comment by neobeppe** [comment]
Opened a PR for horizontal support, #15

**Comment by apang42** [comment]
Hi @FengDeng , thanks for flagging this issue! We recently added support for horizontal stackviews here: https://github.com/airbnb/AloeStackView/pull/66
