### ISSUE TITLE
Setting the stack view in a tableHeaderView

### ISSUE THREAD

**Issue by reshadf** [airbnb/AloeStackView#44]
Trying to set the stackView as the view of my tableHeaderview, The height becomes 0. See code example below. I tried settings constraints on my headerView, the stackview and even the tableHeaderView but I can't seem to get it to work. Am I overseeing something? 

```
let headerStackView = AloeStackView()
        headerStackView.hidesSeparatorsByDefault = true
        headerStackView.addRow(headerView)
        
  
        tableView.tableHeaderView = headerView // using this works
        tableView.tableHeaderView = headerStackView // using this doesn't
```

**Comment by florianldt** [comment]
Hi, a possible issue may be that your `headerView ` might have frame constraints but your `headerStackView` doesn't.

If I understand well, this [Gist] (https://gist.github.com/florianldt/3cd0de5464599505100b6a43f723a27c) might help.

Demo: 
![AloeStackView#44](https://user-images.githubusercontent.com/9365651/55014367-320de580-502e-11e9-8a80-439cd0e90d10.gif)

Hope it helps

**Comment by apang42** [comment]
Hi @reshadf , thanks for reaching out! Since AloeStackView has a UIScrollView and so does UITableView, nesting them wouldn't work properly. Instead of doing this, you could consider setting a UIStackView as the headerView of the UITableView. Feel free to reopen this if you have any questions about this.
