### ISSUE TITLE
Embedding TableView as row

### ISSUE THREAD

**Issue by nomad10101** [airbnb/AloeStackView#69]
Can I embed a UITableView as a row? I am unable to accomplish this currently. The containing AloeStackView seems to ignore the TableView contents. TableView datasource function (func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell) is never called.

**Comment by apang42** [comment]
Hi @nomad10101, thanks for reaching out! Putting a UITableView inside an AloeStackView is not supported. Since AloeStackView has UIScrollView and so does UITableView, nesting them wouldn't work properly. Instead of doing this, you could consider adding the contents of the table view to the stack view as separate rows, or you could just put everything in a table view and not use a stack view at all. Feel free to reopen this if you have any questions about this.
